name: Trigger auto deployment for snippetbox

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/snippetbox-AutoDeployTrigger-3b4a35aa-df0e-41cd-81eb-193242254ca9.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.SNIPPETBOX_REGISTRY_USERNAME }}
          password: ${{ secrets.SNIPPETBOX_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gophersumit/snippetbox:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SNIPPETBOX_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n snippetbox -g DBs --server docker.io --username  ${{ secrets.SNIPPETBOX_REGISTRY_USERNAME }} --password ${{ secrets.SNIPPETBOX_REGISTRY_PASSWORD }}
            az containerapp update -n snippetbox -g DBs --image gophersumit/snippetbox:${{ github.sha }}
